<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Kur;
use Doctrine\ORM\EntityRepository;

/**
 * KurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KurRepository extends EntityRepository
{

}
